# Generated by Django 3.1.6 on 2021-05-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=5, default=0, max_digits=28, null=True)),
                ('selling_rice', models.DecimalField(decimal_places=5, default=0, max_digits=28, null=True)),
            ],
        ),
    ]
