# Generated by Django 3.1.6 on 2021-05-04 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_shipment_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='selling_rice',
            new_name='selling_price',
        ),
    ]
