# Generated by Django 3.1.6 on 2021-05-03 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=5, default=0, max_digits=28, null=True)),
                ('unit_price', models.DecimalField(decimal_places=5, default=0, max_digits=28, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=50)),
                ('or_number', models.CharField(max_length=50)),
                ('or_date', models.DateField()),
                ('or_amount_total', models.DecimalField(decimal_places=5, default=0, max_digits=28, null=True)),
                ('shipment_items', models.ManyToManyField(to='shipment.ShipmentLines')),
            ],
        ),
    ]
